#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff HEAD~ HEAD --name-only | grep -E '^(package-lock\.json|yarn\.lock)$';
then 
    echo -e "Detected changes in dependencies, executing npm install..." 
    npm i
fi

exit 0

